### ISSUE TITLE
Non-ASCII path names in repo

### ISSUE THREAD

**Issue by teeks99** [boostorg/boostdep#8]
I know this was intentional, but the addition of non-ascii path names caused scripts I had running (python 2 shutil.copytree on windows) to fail. Others may experience other issues with this.

**Comment by pdimov** [comment]
Right. The point of the path names was to check that my `depinst` script didn't fail. :-) I realize this might cause problems; any suggestions as to how I can fix that while retaining the test?

**Comment by pdimov** [comment]
Fixed.

**Comment by teeks99** [comment]
Thanks. 

I also added this thread on the mailing list for broader discussion:
https://lists.boost.org/Archives/boost/2018/10/243784.php
